apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    port 6379
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes

    # 클러스터 재지정 응답을 DNS로 주기 위해 선언
    cluster-announce-ip ${POD_NAME}.redis.redis.svc.cluster.local
    cluster-announce-port 6379
    cluster-announce-bus-port 16379
